# Generated by Django 4.1.5 on 2023-01-16 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_direecion_ippost_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ip',
            field=models.CharField(max_length=12),
        ),
    ]
